plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.junit.jupiter:junit-jupiter:5.12.2'
    implementation 'org.junit.platform:junit-platform-launcher:1.12.2'
    implementation 'org.apiguardian:apiguardian-api:1.1.2'
    implementation 'org.javassist:javassist:3.30.2-GA'
    implementation 'com.google.protobuf:protobuf-java:4.31.1'
    implementation 'com.mchange:c3p0:0.11.0'
    implementation 'org.slf4j:slf4j-api:2.0.17'
    implementation 'org.hamcrest:hamcrest:3.0'
    implementation 'com.oracle.oci.sdk:oci-java-sdk-common:3.66.0'
    implementation 'io.opentelemetry:opentelemetry-api:1.50.0'
    implementation 'org.apache.ant:ant-junitlauncher:1.10.15'
    implementation 'org.apache.ant:ant-junit:1.10.15'
}

task downloadDependencies(type: Copy) {
    description = 'Downloads all runtime dependencies into the libs folder'
    from configurations.runtimeClasspath
    into '.'
}
